#AndroidIDE: enforce UTF-8 & locale for Gradle daemon
#Wed Apr 29 12:21:22 GMT 2026
android.nonTransitiveRClass=false
systemProp.user.language=en
systemProp.user.country=US
systemProp.sun.jnu.encoding=UTF-8
systemProp.file.encoding=UTF-8
android.injected.testOnly=false
org.gradle.jvmargs=-Xmx4g -Dfile.encoding\=UTF-8 -XX\:+UseParallelGC -Dorg.gradle.warning.mode\=all
android.useAndroidX=true
android.enableJetifier=false
