# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
android.enableJetifier=false
android.injected.testOnly=false
android.nonTransitiveRClass=false
android.useAndroidX=true
org.gradle.configureondemand=false
org.gradle.daemon=true
org.gradle.daemon.idletimeout=10800000
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -XX:+UseParallelGC -Dorg.gradle.warning.mode=all
org.gradle.parallel=true
systemProp.file.encoding=UTF-8
systemProp.sun.jnu.encoding=UTF-8
systemProp.user.country=US
systemProp.user.language=en
