package pro.sketchware.ai.chat.model;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import java.util.UUID;

/**
 * ChatMessage — Unified message model for the entire AI Chat Platform.
 *
 * <p>This is the SINGLE SOURCE OF TRUTH for all message data across:
 * <ul>
 *   <li>ChatActivity (full-screen chat)</li>
 *   <li>ChatBottomSheetFragment (embedded assistant panel)</li>
 * </ul>
 *
 * <p>Message Types:
 * <ul>
 *   <li>{@link MessageType#USER}               — message sent by the user</li>
 *   <li>{@link MessageType#AI}                 — response from the AI model</li>
 *   <li>{@link MessageType#SYSTEM}             — internal system notification (not sent to AI)</li>
 *   <li>{@link MessageType#TOOL}               — result from a tool execution</li>
 *   <li>{@link MessageType#INTERNAL_ASSISTANT} — internal assistant message (visible in chat)</li>
 * </ul>
 *
 * <p>Status values track message lifecycle:
 * <ul>
 *   <li>{@link MessageStatus#SENDING}  — message is in transit / AI is generating</li>
 *   <li>{@link MessageStatus#SENT}     — message delivered / AI response complete</li>
 *   <li>{@link MessageStatus#ERROR}    — message failed to send or AI returned an error</li>
 * </ul>
 *
 * <p>Design rules:
 * <ul>
 *   <li>All fields are final except {@code text}, {@code status}, and {@code isStreaming}.</li>
 *   <li>Use static factory methods instead of constructors for clarity.</li>
 *   <li>DiffUtil comparisons use {@code id} for identity and the full payload for content.</li>
 * </ul>
 */
public final class ChatMessage {

    // ─── Message Types ───────────────────────────────────────────────────────

    public enum MessageType {
        /** Message written and sent by the human user. */
        USER,
        /** Response generated by the AI model. */
        AI,
        /** System-level notification shown inside the chat (e.g. "Conversation cleared"). */
        SYSTEM,
        /** Result returned by a tool execution (file op, JSON parse, etc.). */
        TOOL,
        /**
         * Visible assistant message generated by the internal assistant layer —
         * used for operations like auto-fix, build results, injected context.
         * Distinct from AI so it can be styled differently and filtered easily.
         */
        INTERNAL_ASSISTANT
    }

    // ─── Message Status ──────────────────────────────────────────────────────

    public enum MessageStatus {
        /** Outgoing: waiting for AI response. Incoming: AI is streaming. */
        SENDING,
        /** Fully delivered or AI generation complete. */
        SENT,
        /** Network error, API failure, or tool execution failure. */
        ERROR
    }

    // ─── Fields ──────────────────────────────────────────────────────────────

    /** Stable unique identifier — used by DiffUtil for identity checks. */
    @NonNull
    private final String id;

    /** Human-readable message content. May be null for tool-only assistant messages. */
    @Nullable
    private String text;

    /** The role/type of this message in the conversation. */
    @NonNull
    private final MessageType type;

    /** Unix epoch milliseconds when the message was created. */
    private final long timestamp;

    /** Current delivery/generation status. */
    @NonNull
    private MessageStatus status;

    /**
     * True while the AI is actively streaming tokens into this message.
     * Transient: not persisted to disk.
     */
    private transient boolean isStreaming;

    /**
     * Optional conversation ID this message belongs to.
     * Null for ephemeral / BottomSheet-only messages.
     */
    @Nullable
    private final String conversationId;

    /**
     * Optional tool name — populated for {@link MessageType#TOOL} messages.
     */
    @Nullable
    private final String toolName;

    /**
     * Optional tool call ID — links a tool result back to its tool call.
     */
    @Nullable
    private final String toolCallId;

    // ─── Private Constructor ──────────────────────────────────────────────────

    private ChatMessage(
            @NonNull String id,
            @Nullable String text,
            @NonNull MessageType type,
            long timestamp,
            @NonNull MessageStatus status,
            @Nullable String conversationId,
            @Nullable String toolName,
            @Nullable String toolCallId
    ) {
        this.id = id;
        this.text = text;
        this.type = type;
        this.timestamp = timestamp;
        this.status = status;
        this.isStreaming = false;
        this.conversationId = conversationId;
        this.toolName = toolName;
        this.toolCallId = toolCallId;
    }

    // ─── Static Factory Methods ───────────────────────────────────────────────

    /**
     * Creates a user message with {@link MessageStatus#SENDING} status.
     * Status should be updated to {@link MessageStatus#SENT} once the AI starts responding.
     */
    @NonNull
    public static ChatMessage user(@NonNull String text) {
        return new ChatMessage(
                UUID.randomUUID().toString(),
                text,
                MessageType.USER,
                System.currentTimeMillis(),
                MessageStatus.SENDING,
                null, null, null
        );
    }

    /**
     * Creates a user message linked to a specific conversation.
     */
    @NonNull
    public static ChatMessage user(@NonNull String text, @Nullable String conversationId) {
        return new ChatMessage(
                UUID.randomUUID().toString(),
                text,
                MessageType.USER,
                System.currentTimeMillis(),
                MessageStatus.SENDING,
                conversationId, null, null
        );
    }

    /**
     * Creates an AI message placeholder with {@link MessageStatus#SENDING}.
     * Text will be streamed in via {@link #appendText(String)}.
     */
    @NonNull
    public static ChatMessage aiPlaceholder() {
        return new ChatMessage(
                UUID.randomUUID().toString(),
                null,
                MessageType.AI,
                System.currentTimeMillis(),
                MessageStatus.SENDING,
                null, null, null
        );
    }

    /**
     * Creates a complete AI message with {@link MessageStatus#SENT}.
     */
    @NonNull
    public static ChatMessage ai(@NonNull String text) {
        return new ChatMessage(
                UUID.randomUUID().toString(),
                text,
                MessageType.AI,
                System.currentTimeMillis(),
                MessageStatus.SENT,
                null, null, null
        );
    }

    /**
     * Creates a SYSTEM-type notification message.
     * These are shown as banners in the message list and are NOT sent to the AI API.
     */
    @NonNull
    public static ChatMessage system(@NonNull String text) {
        return new ChatMessage(
                UUID.randomUUID().toString(),
                text,
                MessageType.SYSTEM,
                System.currentTimeMillis(),
                MessageStatus.SENT,
                null, null, null
        );
    }

    /**
     * Creates a TOOL result message.
     *
     * @param toolName   the name of the tool that produced this result
     * @param toolCallId the ID linking this result to its originating tool call
     * @param text       the tool result content (may be JSON or plain text)
     */
    @NonNull
    public static ChatMessage tool(
            @NonNull String toolName,
            @NonNull String toolCallId,
            @NonNull String text
    ) {
        return new ChatMessage(
                UUID.randomUUID().toString(),
                text,
                MessageType.TOOL,
                System.currentTimeMillis(),
                MessageStatus.SENT,
                null, toolName, toolCallId
        );
    }

    /**
     * Creates an INTERNAL_ASSISTANT message.
     * Displayed in the chat list but originated by internal platform logic
     * (auto-fix, build status, injected context, etc.).
     */
    @NonNull
    public static ChatMessage internalAssistant(@NonNull String text) {
        return new ChatMessage(
                UUID.randomUUID().toString(),
                text,
                MessageType.INTERNAL_ASSISTANT,
                System.currentTimeMillis(),
                MessageStatus.SENT,
                null, null, null
        );
    }

    /**
     * Creates an error message for a failed AI response or failed send.
     *
     * @param originalText the user's original text that failed, may be null
     * @param errorDetail  description of the failure
     */
    @NonNull
    public static ChatMessage error(@Nullable String originalText, @NonNull String errorDetail) {
        return new ChatMessage(
                UUID.randomUUID().toString(),
                errorDetail,
                MessageType.AI,
                System.currentTimeMillis(),
                MessageStatus.ERROR,
                null, null, null
        );
    }

    // ─── Getters ──────────────────────────────────────────────────────────────

    @NonNull
    public String getId() {
        return id;
    }

    @Nullable
    public String getText() {
        return text;
    }

    @NonNull
    public MessageType getType() {
        return type;
    }

    public long getTimestamp() {
        return timestamp;
    }

    @NonNull
    public MessageStatus getStatus() {
        return status;
    }

    public boolean isStreaming() {
        return isStreaming;
    }

    @Nullable
    public String getConversationId() {
        return conversationId;
    }

    @Nullable
    public String getToolName() {
        return toolName;
    }

    @Nullable
    public String getToolCallId() {
        return toolCallId;
    }

    // ─── Mutators (only for streaming / status updates) ───────────────────────

    /**
     * Sets the delivery/generation status of this message.
     * Called by {@link pro.sketchware.ai.chat.coordinator.ChatCoordinator}.
     */
    public void setStatus(@NonNull MessageStatus status) {
        this.status = status;
    }

    /**
     * Marks this message as actively streaming from the AI.
     * Setting to false signals streaming is complete.
     */
    public void setStreaming(boolean streaming) {
        this.isStreaming = streaming;
    }

    /**
     * Replaces the full text content of this message.
     * Used when overwriting an AI placeholder after streaming completes.
     */
    public void setText(@Nullable String text) {
        this.text = text;
    }

    /**
     * Appends a token chunk during streaming.
     * Thread-safe string append — called from the AI streaming callback.
     */
    public synchronized void appendText(@NonNull String chunk) {
        if (this.text == null) {
            this.text = chunk;
        } else {
            this.text = this.text + chunk;
        }
    }

    // ─── Helper predicates ───────────────────────────────────────────────────

    /** True if this message originated from the user side. */
    public boolean isFromUser() {
        return type == MessageType.USER;
    }

    /** True if this message is from the AI or internal assistant. */
    public boolean isFromAi() {
        return type == MessageType.AI || type == MessageType.INTERNAL_ASSISTANT;
    }

    /** True if this message has non-empty visible text. */
    public boolean hasText() {
        return text != null && !text.trim().isEmpty();
    }

    /** True if this message is in a failed state. */
    public boolean isError() {
        return status == MessageStatus.ERROR;
    }

    // ─── DiffUtil support ─────────────────────────────────────────────────────

    /**
     * Content equality check for DiffUtil — compares all visible payload fields.
     * Called by {@link pro.sketchware.ai.chat.adapter.ChatMessageDiffCallback#areContentsTheSame}.
     */
    public boolean contentEquals(@NonNull ChatMessage other) {
        if (!id.equals(other.id)) return false;
        if (type != other.type) return false;
        if (status != other.status) return false;
        if (isStreaming != other.isStreaming) return false;
        if (timestamp != other.timestamp) return false;
        // Text comparison (null-safe)
        if (text == null && other.text != null) return false;
        if (text != null && !text.equals(other.text)) return false;
        return true;
    }

    @NonNull
    @Override
    public String toString() {
        return "ChatMessage{"
                + "id='" + id + '\''
                + ", type=" + type
                + ", status=" + status
                + ", textLen=" + (text != null ? text.length() : 0)
                + ", streaming=" + isStreaming
                + '}';
    }
}
